---
- name: Example playbook for POC-leumi
  hosts: localhost
 

  tasks: 
   
  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
      vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
      vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"


    register: my_datacenters


