---
- name: Example playbook for POC-leumi
  hosts: localhost
 

  tasks: 
   
  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_validate_certs: false
    register: my_datacenters


