---
- name: Example playbook for POC
  hosts: all
 

  tasks: 
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install latest bind-utils
      ansible.builtin.package:
        name: bind-utils
        state: latest


