---
- name: Example playbook for POC-leumi
  hosts: localhost
 

  tasks: 
  - name: Build a list of all the folders
    vmware.vmware_rest.vcenter_folder_info:
    register: vc_folders

  - name: Display vc_folders
    ansible.builtin.debug:
      var: vc_folders
      verbosity: 0

  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_validate_certs: false
    register: vc_datacenters

  - name: Display vc_datacenters
    ansible.builtin.debug:
      var: vc_datacenters
      verbosity: 0

  - name: Create a sample VM
    vmware.vmware_rest.vcenter_vm:
      vcenter_validate_certs: false
      placement:
        cluster: Cluster-1
        datastore: WorkloadDatastore
        folder: /SDDC-Datacenter/Workloads/sandbox-cfjkw/
        resource_pool: "{{ lookup('vmware.vmware_rest.resource_pool_moid', '/my_dc/host/my_cluster/Resources') }}"  
      name: test_vm1
      guest_OS: RHEL_7_64
      hardware_version: VMX_11
      memory:
        hot_add_enabled: true
        size_MiB: 1024
    register: my_vm



