---
- name: Example playbook for POC
  hosts: all
 

  tasks: 
    - include_role:
        name: community.zabbix.zabbix_agent
      vars:
        zabbix_agent_server: "{{ zbx_agent_server }}"
        zabbix_agent_serveractive: "{{ zbx_agent_serveractive }}"
        zabbix_agent_hostname: "{{ zbx_agent_hostname }}" 
        zabbix_agent_timeout: "{{ zbx_agent_timeout }}"
        zabbix_agent_dont_detect_ip: "{{ zbx_agent_dont_detect_ip }}"
        zabbix_agent_chassis: "{{ zbx_agent_chassis }}"
        zabbix_agent_userparameters:
          - name: mysql
            scripts_dir: mysql
          - name: galera
          
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install latest bind-utils
      ansible.builtin.package:
        name: bind-utils
        state: latest


