---
- name: Example playbook for POC-leumi
  hosts: localhost
 

  tasks: 
   
  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_hostname: '{{ VMWARE_HOST }}'
      vcenter_username: '{{ VMWARE_USER }}'
      vcenter_password: '{{ VMWARE_PASSWORD }}'
    register: my_datacenters


