---
- name: Example playbook for POC-leumi
  hosts: localhost
 

  tasks: 
  - name: Create a sample VM
    vmware.vmware_rest.vcenter_vm:
      vcenter_validate_certs: false
      placement:
        cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/my_dc/host/my_cluster') }}"
        datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/my_dc/datastore/rw_datastore') }}"
        folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm') }}"
        resource_pool: "{{ lookup('vmware.vmware_rest.resource_pool_moid', '/my_dc/host/my_cluster/Resources') }}"  
      name: test_vm1
      guest_OS: RHEL_7_64
      hardware_version: VMX_11
      memory:
        hot_add_enabled: true
        size_MiB: 1024
    register: my_vm

  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_validate_certs: false
    register: my_datacenters


