---
- name: Example playbook for POC-leumi
  hosts: all
 

  tasks: 

    - include_role:
        name: vmware.vmware_rest.vcenter_vm
      vars:
        vcenter_vm_hostname: "{{ vcenter_hostname }}"
        vcenter_vm_username: "{{ vcenter_username }}"
        vcenter_vm_password: "{{ vcenter_password }}" 
        vcenter_vm_name: "{{ vm_name }}"
        vcenter_vm_validate_certs: "{{ vcenter_validate_certs }}"
      
    
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:        
      
          placement:
            cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/my_dc/host/my_cluster') }}"
            datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/my_dc/datastore/rw_datastore') }}"
            folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm') }}"
            resource_pool: "{{ lookup('vmware.vmware_rest.resource_pool_moid', '/my_dc/host/my_cluster/Resources') }}"
          name: test_vm1
          guest_OS: RHEL_7_64
          hardware_version: VMX_11
          memory:
            hot_add_enabled: true
            size_MiB: 1024
      register: my_vm


